### ISSUE TITLE
Top nav type size from 16px to 14px

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#1037]
Please swith the top nav type size in GT to 14px. Works better when more than 3 items in the nav. 

This would apply to 

www.ibm.com/design
https://www.ibm.com/able/

and the new site Ryan is working on which looks like it’s already 14px
https://w3.ibm.com/design/racial-equity-in-design/

![image (13).png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/9fa112d4-dce7-4488-a8db-d4a971a99424)

——————

![image (8).png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/ed9889ca-2d74-416b-8392-1a5edec79133)

**Comment by mjabbink** [comment]
FYI @jeanservaas @sadekbazaraa agree?

**Comment by sadekbazaraa** [comment]
@mjabbink @jeanservaas I was going to ask about this actually! My first instinct is that 14px is pretty small in the masthead. I know there may be a site or two that could benefit from some space saving moves but I wonder if it doesn't feel too diminished? Especially with the masthead type in the upper left. Most of our sites don't have top nav links and I'd hate to lose the weight of the main masthead text if we don't need to. That being said, I could be swayed. 

Somewhere along the way, I remember asking Be Equal to fix the masthead because they're using 14px links. We can see a live example here. Feels a bit small to me. https://www.ibm.com/impact/be-equal/

The other option as in the BE example is to consider keeping the main masthead 16px with 14px links as a happy medium but even that feels a little unnecessarily fussy.
