### ISSUE TITLE
image compression

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#111]
@vpicone @alisonjoseph Look at the same GIF in the two pages/sites below. You’ll notice the Carb one is getting further compressed somehow. It’s happening in other gigs and images within the Carb site as well, like in Style tabs where images exist. 

Check out “Introduction” section
——
DL
https://www.ibm.com/design/language/elements/color-ui

——
Carb
https://www.carbondesignsystem.com/guidelines/color/overview

**Comment by vpicone** [comment]
Going to copy my response to the enterprise thread here and also add it to the README

The issue here is with the quality of the source photos. Leveraging gatsby-image requires you to provide full resolution, quality images. This is _especially_ true when the image is a photo rather than an illustration. The compression plugin breaks down with large images with relatively low pixel density. Full resolution photos from unsplash, IBM Digital assets, etc. routinely run 7-10mb. The `ibmer-4` image above is just 548kb in the src folder. Even the highest resolution photos (like dear-tech above) are just 3mb.

It's possible to over-ride the default quality of the gatsby plugin. But my _strong_ recommendation would be to provide higher quality source images and let gatsby-image really do it's magic with image optimization. 

If these are _truly_ the highest resolution we can procure for these images, you can add the following to your gatsby-config and tweak the default optimization to your performance/quality needs:

```js
module.exports = {
  siteMetadata: {
    title: 'Gatsby Theme Carbon'
  },
  __experimentalThemes: [
    {
      resolve: 'gatsby-theme-carbon',
      options: {
        name: 'Gatsby Theme Carbon Starter',
        shortName: 'Carbon Starter'
      }
    }
  ],
  plugins: [{ resolve: `gatsby-plugin-sharp`, options: { defaultQuality: 80 } }]
}
```

**Comment by vpicone** [comment]
closed with https://github.com/carbon-design-system/gatsby-theme-carbon/commit/af32bd40e610ca085ae0a286c09d4e63c141befd
