### ISSUE TITLE
Resource Card Group enhancement - add 3 across option

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/gatsby-theme-carbon#1375]
From @mjabbink 

> It has always been the intent to get resource cards to be go across the page in 2 or 3. However it was developed to be only 2. 
> 
> The Carbon example shows how 3 would be a more efficient solution as well as look better. 
> https://carbondesignsystem.com/#other-resources
> 
> In the Carbon for ibm.com since there’s only three it wold also benefit from being 3 across (simplified)
> https://ibmdotcom-library.s3-web.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/1688/

Current design - only option is 2 across
<img width="1159" alt="Screenshot 2023-11-29 at 8 55 24 AM" src="https://github.com/carbon-design-system/gatsby-theme-carbon/assets/2753488/e75aff92-b756-445f-975e-73f8fc11caea">

Option to be added (an example of 3 across)

<img width="1208" alt="Screenshot 2023-11-29 at 8 59 00 AM" src="https://github.com/carbon-design-system/gatsby-theme-carbon/assets/2753488/77eb57f8-0bf7-4b39-8831-2ae427bca8fb">

Current code that creates correct borders and span only two across
```
<Row className="resource-card-group">
  <Column colMd={4} colLg={4} noGutterSm>
    <ResourceCard...... 
```

One suggestion is adding a new component, `CardGroup`, similar to what we did in Platform, and then add a prop to choose how many show across, with the default being 2. 

Possibly `cardSpan`? or `cardsPerRow`?
```
<CardGroup cardSpan={3}>
 <Column colMd={4} colLg={4} noGutterSm>
    <ResourceCard...... />
```

OR a simple option is to just add an additional class-name to add correct styling
```
<Row className="resource-card-group-3-across">
  <Column colMd={4} colLg={4} noGutterSm>
    <ResourceCard...... 
```

**Comment by mjabbink** [comment]
Thanks @alisonjoseph. Maybe whoever did it for IDL and brand center can contribute?

https://www.ibm.com/design/language/

https://www.ibm.com/brand/

**Comment by glapadre** [comment]
Hello! We would love to use this feature on the new [PAL homepage](https://github.ibm.com/CDAI-design/pal/issues/1391) as seen below, but we are currently using `gatsby-theme-carbon: `2.3.2`` 
![Screenshot 2024-01-17 at 11 32 50 AM](https://github.com/carbon-design-system/gatsby-theme-carbon/assets/25260547/e709527d-f8ee-4a3d-be70-000d52baf903)

I'm able to get the cards to align across in three cards, but I'm having issues with the border. I assume this is because we're on a old version of `gatsby-theme-carbon` making our `scss` version outdated. 

Curious if I can use this new enhancement on the old version of Gatsby or if we need to upgrade to use it.. This is my current localhost version which I'm having trouble displaying the borders. 

![Screenshot 2024-01-17 at 11 41 53 AM](https://github.com/carbon-design-system/gatsby-theme-carbon/assets/25260547/579aca25-e6e2-4a7f-bc17-26771704ae10)
