### ISSUE TITLE
Bug [image card]: card not flush on right side of image

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#464]
@jeanservaas @alisonjoseph 

![Screen Shot 2019-10-04 at 1 58 08 PM](https://user-images.githubusercontent.com/32881239/66232765-43a40a00-e6af-11e9-89b2-78a211a4c015.png)

![Screen Shot 2019-10-04 at 1 58 00 PM](https://user-images.githubusercontent.com/32881239/66232766-43a40a00-e6af-11e9-8de5-6fc49c1454dc.png)

**Comment by jnm2377** [comment]
I'm looking into this, but I can't reproduce on the gatsby theme. I'm wondering why the example `FeatureCard` doesn't have this bug. When I inspect both sites, it seems that they're both getting the _exact_ same styles but for some reason, the carbon website is off by `8px` _only_ in the `max` breakpoint, all the other breakpoints are flush. @vpicone any idea what could be happening here?

**gatsby theme example:** flush at all breakpoints

<img width="1187" alt="Screen Shot 2019-10-09 at 1 58 04 PM" src="https://user-images.githubusercontent.com/32556167/66511674-feac1900-ea9c-11e9-901b-2ed903e7a043.png">

**Comment by mjabbink** [comment]
Looks like it’s not happening in the Gatsby site. Only in Carbon and Brand Center sites (below).


<img width="1604" alt="Screen Shot 2019-10-11 at 6 52 00 PM" src="https://user-images.githubusercontent.com/32881239/66690834-517e0000-ec58-11e9-95a5-b378be3dbe70.png">

**Comment by alisonjoseph** [comment]
We might just need to adjust the right padding at the max breakpoint to be 8px instead of 16px. I'm on my tiny laptop screen which is making it kind of hard to debug.

**Comment by abid-din-akqa** [comment]
@jnm2377 @alisonjoseph I've been attempting to debug this recently whilst working on the Watson/Cloud Brand Tool sites.

Some additional details that may help:

- It seems to have started happening since upgrading to the latest version of Gatsby Theme Carbon (hard to say which version exactly could be the cause, since the Watson/Cloud sites were originally using a much older version - v1.6.0).

- Oddly, all the styles between the live (working) example and the broken version appear exactly the same, but calculated values are off.

- As above, it's odd the GTC site doesn't exhibit this issue, given we're using the latest version of GTC (which I believe the GTC site is, also).

Wondering if an underlying dependency has been updated (rows, Resourcecard, or similar) and thus there are child package discrepancies (seems less likely).

**Comment by mjabbink** [comment]
I’ll add it’s only beyond extra large breakpoints as well. Basically on large displays. On a laptop only it will not be visible

**Comment by alisonjoseph** [comment]
https://pages.github.ibm.com/brand/events/brand-expression/

another example of the issue. spacing seems different w/ videos/svg
