### ISSUE TITLE
[Row] please add prop to remove top margin

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/gatsby-theme-carbon#535]
### Summary

All `Row` components in the main body of the page have a default `margin-top` value:

![Screen Shot 2019-11-15 at 3 29 52 PM](https://user-images.githubusercontent.com/9057921/68977053-eeced580-07bc-11ea-8834-b0a98aa53633.png)

These lines appear to be the cause:

https://github.com/carbon-design-system/gatsby-theme-carbon/blob/7ad684f52441975d4452d33d96cfd3093f7733b6/packages/gatsby-theme-carbon/src/components/Main/Main.module.scss#L11-L14

But unlike the `Column` component, there's no prop to remove this spacing if needed.

We would like to have a prop we could use for the `Row` component that removes this margin value.

### Justification

There are instances in IBM Security designs where there are no margins between rows, so we would like the flexibility to remove these margins easily without a messy style override.

**Comment by jendowns** [comment]
@jnm2377 Is this related to your spacing work, or slightly different? I could help with this if needed. 👍

**Comment by jnm2377** [comment]
Hey @jendowns this would be related to the spacing work. These styles may be changing soon, I'm still auditing everything that was affected to figure out a work around for everything. I can definitely keep you in the loop about this.

**Comment by jnm2377** [comment]
I think either way, it would be fine to add an option to remove the margin since Column does that as well. But just wanted to you to know that the styles may be changing with this second space audit.

**Comment by jendowns** [comment]
That sounds good @jnm2377 -- thank you! We have a way around this with a style override at the moment. So I'll watch for updates 👍

**Comment by jnm2377** [comment]
@jendowns after talking to Vince about this, it seems that we want to intentionally give a margin to any direct children of `main`. However, we tried doing it in the least specific way possible to allow for easy overrides. Presently, the two easiest ways to override this would be to set `--space: 0`:

``` 
 .main > * + * { 
  --space: 0;
 }
```

 or to contain the rows in a div or some other element so that they are no longer direct children of main. This would give the row container the margin-top instead of the rows themselves.

**Comment by jendowns** [comment]
Thanks @jnm2377 -- that's similar to what we've done now. So I take it there aren't plans to add a prop that removes margins/spacing in the future? Should I close this one out?

**Comment by vpicone** [comment]
@jendowns yeah its nothing special about rows, that space just gets added to top level children. Wrapping the rows (or any group of elements) will prevent them from each getting the margin top. 

Sorry for the break, it was a pretty big shift in how we handle vertical rhythm. I’d prefer wrapping the rows rather than adding a prop to each row, I’m not a fan of how copy-and-paste repetitive the column props are.

**Comment by jendowns** [comment]
Yeah no worries, I'll close this one out then
