### ISSUE TITLE
2 December launch: Enable “Events” link in site Switcher

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#539]
Please coordinate with Ken Hartmann and @greeshmareddyg on this issue.

URL: www.ibm.com/design/events

current (disabled view)
<img width="249" alt="Screen Shot 2019-11-15 at 2 27 36 PM" src="https://user-images.githubusercontent.com/32881239/69163467-deb44000-0ab3-11ea-9dfb-f8aeb3e8fe5d.png">

expected (Dec 2):

<img width="248" alt="Screen Shot 2019-11-19 at 10 05 44 AM" src="https://user-images.githubusercontent.com/32881239/69163651-3652ab80-0ab4-11ea-825f-b1e759c27d49.png">

**Comment by mjabbink** [comment]
related to https://github.com/carbon-design-system/gatsby-theme-carbon/issues/537

**Comment by alisonjoseph** [comment]
- [ ] Update "Events" link in switcher to point to `https://www.ibm.com/design/events/`
- [ ] Publish theme update

Website's that need to pull in update

- [ ] Carbon
- [ ] IDL
- [ ] Brand
- [ ] Research
- [ ] AI
- [ ] /design _(doesn't use the theme)_ https://github.com/IBM-Design/design-website

Theme update needs to be published before 12/2 so that the Events site can go live w/ correct links in the switcher. 

@jnm2377

**Comment by mjabbink** [comment]
Last minute update from Event team:

- [ ]  Update switcher from "Events" to singular "Event"

- [ ] Update "Event" link in switcher to point to https://www.ibm.com/design/event/

**Comment by mjabbink** [comment]
<img width="248" alt="Screen Shot 2019-11-19 at 10 05 44 AM" src="https://user-images.githubusercontent.com/32881239/69202028-e7356680-0b05-11ea-9026-c92909237a49.png">
