### ISSUE TITLE
Refactor DoDont component

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/gatsby-theme-carbon#592]
Consider adding a `DoDontRow` along with a `Do` and a `Dont` component. 

That way we can tuck away all the row AND column nonsense (while passing through row/col props in case they want to adjust sizes). This has the added benefit of not breaking previous uses of DoDontExample with manual Row and Column.

Should also refactor to use css modules

**Comment by alisonjoseph** [comment]
Would really prefer we don't add a new Do/Dont component. This component is used across many sites in many places and would be big breaking change. I know that it wouldn't break previous versions, but if the styles are different then it would break because they wouldn't get updated. We could add a DoDontRow, or we could add a custom class name to use.
