### ISSUE TITLE
caption spacing update

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#613]
In one of the caption (below) there is an extra 4px or so under the image which is adding additional space above caption. This extra space under image should be removed.
https://gatsby-theme-carbon.now.sh/components/Caption#example

<img width="855" alt="Screen Shot 2019-12-14 at 3 52 49 PM" src="https://user-images.githubusercontent.com/32881239/70855057-12ec0800-1e8a-11ea-8b51-2b2be9e6b073.png">

Other examples in IDL site

<img width="857" alt="Screen Shot 2019-12-14 at 3 48 55 PM" src="https://user-images.githubusercontent.com/32881239/70855064-2303e780-1e8a-11ea-93bd-e036463982dc.png">

————

<img width="868" alt="Screen Shot 2019-12-14 at 3 47 32 PM" src="https://user-images.githubusercontent.com/32881239/70855065-2b5c2280-1e8a-11ea-8bf3-1db90852278f.png">

————

<img width="873" alt="Screen Shot 2019-12-14 at 3 45 42 PM" src="https://user-images.githubusercontent.com/32881239/70855067-357e2100-1e8a-11ea-879f-575a20107bad.png">

**Comment by alisonjoseph** [comment]
@vpicone can this be closed w/ your latest caption fix?

**Comment by jnm2377** [comment]
Ah, looks like this issue is coming from the image. I thought this was just happening in the IDL site and had opened a PR there in December (https://github.com/jnm2377/design-language-website/blob/3649a124dc933f594985d85cb6257bca86333676/src/styles/_images.scss#L14)

Will add the `display: block` for images in Gatsby as well. I think that should do it.

**Comment by mjabbink** [comment]
The first image sample is from Gatsby them site not just IDL site. It is happening across the them sites.
