### ISSUE TITLE
Add video scrubbing to Video component

### ISSUE THREAD

**Issue by ENG618** [carbon-design-system/gatsby-theme-carbon#876]
### Summary

It would be nice if the `<Video>` component had a scrubbing feature when using `src`. So when playing long videos you would be able to skip forward or rewind while watching.  Also, you would be able to see the length of the video.

### Justification

We have long tutorial videos that are not meant to simply play through.  There is a need to replay sections and go through the video in more detail.  And you would be able to see the length of the video

### Desired UX and success metrics

Once the video has begun to play on hover you would see a progress bar over the bottom of the video that would show a basic video control interface.

### Must-have functionality

- a bar showing progress
- progress time
- total time
- play/pause button
- click along the progress time to select a specific time in the video to play.

### Specific timeline issues / requests

N/A

**Comment by jnm2377** [comment]
Hi @ENG618 thanks for opening this issue. We created the custom controls for self hosting videos in order to follow brand design/guidelines for our Carbon website. However, if you use the Video component with videos hosted on Vimeo, it'll have the scrubbing functionality. At the moment, we don't have the capacity to work on a custom progress bar with ffwd/rwd for self hosted videos.

**Comment by vpicone** [comment]
Hey! Gonna close this out for now as we don't have the bandwidth to pick up outside feature requests. This might make for a great contribution though!
