### ISSUE TITLE
32px vertical spacing between Images, Cards, Video, Do nots when stacked desktop and mobile

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/gatsby-theme-carbon#919]
@sadekbazaraa and @jeanservaas Let’s get our decision on this to set universally across the related components that use that same spacing.

This should not interfere with the specified total spacing between images/captions and the headers. Those are typically 64px or 80px.

In below example shows where both are happening within one section and different components.
https://www.ibm.com/design/language/animation/tips-and-techniques/#examples

**Comment by vpicone** [comment]
For perspective, `24px`/`1.5rem` was chosen as the default space because it's the line-height of our body text. Because text dominates most pages’ layout, it makes for a natural denominator.

For content that's really component/image heavy it loses that appeal. Most sites have implemented some sort of 'image-wrapper', 'photo-wrapper', or 'mock-gallery' component that bumps the space up for these moments. At the minimum we could ship a wrapper like this through the theme and add documentation/guidelines for its use.

**Comment by sadekbazaraa** [comment]
@vpicone I think your comments are well put and reflect my observations as well, that 24px is more effective as a baseline as it relates to text and 32px is more effective as it relates to images.

I think one exercise in determining the default spacing might be to see which things need the least amount of tweaking. Is it easier to tweak a couple of the type specs if 32 is the default or to keep 24 the default and adjust resource cards, feature cards, image galleries, etc.

**Comment by mjabbink** [comment]
Stacking boxes/images are less frequent than stacking typography components and typography stacked above or below boxes/images. It sounds like we have two choices...

1. All default to 24px 

or

2. Do the wrap for boxes/images stacking to create the 32px in those situations.

**Comment by vpicone** [comment]
@mjabbink I think it can be a 1. _and_ 2. situation; we can tweak the gap from columns wrapping independently from the default 24px space.

**Comment by vpicone** [comment]
@mjabbink the link you gave looks properly spaced now on desktop and mobile. Can you give some more specific examples of where this is broken?

**Comment by mjabbink** [comment]
I thought we settled on sticking to 23px after discussing. I failed to close this issue. I think it should be consistent. I made this issue before we discussed and I should have removed this issue.

**Comment by vpicone** [comment]
@mjabbink roger that. It feels like we've whack-a-mole'd most of the edge cases. We can open another issue with if one comes up.

**Comment by mjabbink** [comment]
Let’s stick with the 24px throughout except particular cases which we’ll make issues for. Can you revert those last changes so we go back to 24px?

**Comment by vpicone** [comment]
@mjabbink which last changes? We have touched that spacing stuff for a month-ish. I just closed it going off your previous comment.

**Comment by mjabbink** [comment]
So all 24px spacing is now 32px? Bummer I missed removing this issue. I was good with it all being 24px after we chatted. I agreed that 32px was too large for mobile.

**Comment by mjabbink** [comment]
I guess what I’m seeing once reading above threads is this issue should never have been implemented. I thought we agreed to at k with 23px defaults and leave the above mentioned (issue items) as they were at 24px

**Comment by vpicone** [comment]
@mjabbin sorry, my comment when closing this issue was confusing. 

The default spacing is the same as it's been since the spacing overhaul (24px). The edge cases I was referring to were the 32px spacing we use occasionally for things like the illustration galleries.

Nothing was implemented from this issue.

**Comment by mjabbink** [comment]
Ah, ok. Good to close. I do see some 32px in mobile though so thought you were implementing this issue.
